# Generated by Django 5.2.11 on 2026-02-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Показывать вопрос только если выполнено условие зависимости', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='questionnaires.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='depends_value',
            field=models.CharField(blank=True, help_text='Какое значение должно быть у depends_on (например: sand)', max_length=120),
        ),
    ]
