# Generated by Django 5.2.11 on 2026-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_question_depends_on_question_depends_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='issues_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='processed_data_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processed', 'Processed'), ('needs_info', 'Needs info')], default='draft', max_length=20),
        ),
    ]
