# Generated by Django 5.2.11 on 2026-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_submission_issues_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_review', 'На проверке'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
    ]
