# Generated by Django 5.2.11 on 2026-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='manager_label',
            field=models.CharField(blank=True, help_text='Если заполнено — менеджер увидит это вместо slug', max_length=255, verbose_name='Название для менеджера'),
        ),
    ]
