# Generated by Django 5.2.11 on 2026-03-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_question_manager_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='manager_label',
        ),
    ]
